version: "3"
services:
  # cms:
  #   image: ghost:4.36.1-alpine
  #   # https://ghost.org/docs/config/
  #   # env_file: ./services/cms/.env
  #   volumes:
  #     - ./services/cms/ghost/content:/var/lib/ghost/content
  #   ports:
  #     - 3022:2368
  cms:
    build: ./services/cms/strapi
    volumes:
      - ./services/cms/strapi:/srv/app
    ports:
      - "1337:1337"
