version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: |
          ssh-keyscan $LINODE_IP >> ~/.ssh/known_hosts
          ssh yes@$LINODE_IP << EOF            
            if [ -d ~/app/yeslee.me ]; then
              cd ~/app/yeslee.me/
              git pull
            else
              mkdir -p ~/app/
              cd ~/app/
              git clone git@github.com:hiiamyes/yeslee.me.git
              cd yeslee.me/              
            fi
            sudo ./scripts/build.sh
            sudo ./scripts/start.sh
          EOF
