version: 2.1
jobs:
  build:
    machine: true # uses default image circleci/classic:latest
    steps:
      - checkout
      - run:
          command: |
            # curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            # unzip -qq awscliv2.zip
            # sudo ./aws/install --update
            # aws --version
            cd apps/yeslee-me
            echo ${PORT}
            echo ${NUXT_PUBLIC_GTM_ID}
            touch .env
            cat .env
            ./scripts/config.sh
            # ./scripts/push-web.sh
            # ssh-keyscan ${LINODE_IP} >> ~/.ssh/known_hosts 
            # ssh yes@${LINODE_IP} \<< EOF            
            #   if [ -d ~/app/yeslegit cme.me ]; then
            #     cd ~/app/yeslee.me/
            #     git pull
            #   else
            #     mkdir -p ~/app/
            #     cd ~/app/
            #     git clone git@github.com:hiiamyes/yeslee.me.git
            #     cd yeslee.me/              
            #   fi
            #   cd apps/yeslee-me
            #   ./scripts/pull-web.sh
            #   ./scripts/stop.sh
            #   ./scripts/start.sh
            # EOF
workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            branches:
              only: master
