version: '3.1'

services:
  ghost:
    image: ghost:latest
    container_name: ghost_blog
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./ghost_content:/var/lib/ghost/content
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost

  mysql:
    image: mysql:5.7
    container_name: ghost_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  ghost_content:
  mysql_data:
